// ─── DI Tokens ──────────────────────────────────────────────────────
// All tokens use Symbol + SCREAMING_SNAKE_CASE_TOKEN convention.
// Registered exclusively in composition-root.ts via tsyringe.

// Infrastructure
export const CONFIG_TOKEN = Symbol('CONFIG_TOKEN');
export const LOGGER_TOKEN = Symbol('LOGGER_TOKEN');
export const SQLITE_CONNECTION_TOKEN = Symbol('SQLITE_CONNECTION_TOKEN');
export const EVENT_BUS_TOKEN = Symbol('EVENT_BUS_TOKEN');

// Repositories
export const ORGANIZATION_REPO_TOKEN = Symbol('ORGANIZATION_REPO_TOKEN');
export const ROLE_REPO_TOKEN = Symbol('ROLE_REPO_TOKEN');
export const TASK_REPO_TOKEN = Symbol('TASK_REPO_TOKEN');
export const DISCUSSION_REPO_TOKEN = Symbol('DISCUSSION_REPO_TOKEN');
export const RUN_REPO_TOKEN = Symbol('RUN_REPO_TOKEN');
export const SKILL_REPO_TOKEN = Symbol('SKILL_REPO_TOKEN');
export const COST_ENTRY_REPO_TOKEN = Symbol('COST_ENTRY_REPO_TOKEN');
export const NARRATIVE_REPO_TOKEN = Symbol('NARRATIVE_REPO_TOKEN');
export const PENDING_WAKE_REPO_TOKEN = Symbol('PENDING_WAKE_REPO_TOKEN');
export const SETTINGS_REPO_TOKEN = Symbol('SETTINGS_REPO_TOKEN');

// Application Services
export const ORG_ORCHESTRATOR_TOKEN = Symbol('ORG_ORCHESTRATOR_TOKEN');
export const TASK_SERVICE_TOKEN = Symbol('TASK_SERVICE_TOKEN');
export const TASK_STATE_MACHINE_TOKEN = Symbol('TASK_STATE_MACHINE_TOKEN');
export const CONSENSUS_DETECTOR_TOKEN = Symbol('CONSENSUS_DETECTOR_TOKEN');
export const DISCUSSION_SERVICE_TOKEN = Symbol('DISCUSSION_SERVICE_TOKEN');
export const PROMPT_BUILDER_TOKEN = Symbol('PROMPT_BUILDER_TOKEN');
export const SKILL_SELECTOR_TOKEN = Symbol('SKILL_SELECTOR_TOKEN');
export const NARRATIVE_ENGINE_TOKEN = Symbol('NARRATIVE_ENGINE_TOKEN');
export const EVENT_DIGESTER_TOKEN = Symbol('EVENT_DIGESTER_TOKEN');
export const DECOMPOSITION_ADVISOR_TOKEN = Symbol('DECOMPOSITION_ADVISOR_TOKEN');

// Executors
export const EXECUTOR_TOKEN = Symbol('EXECUTOR_TOKEN');
export const WORKER_SERVICE_TOKEN = Symbol('WORKER_SERVICE_TOKEN');
export const MCP_BRIDGE_TOKEN = Symbol('MCP_BRIDGE_TOKEN');
export const MCP_IPC_SERVER_TOKEN = Symbol('MCP_IPC_SERVER_TOKEN');

// Workflow Engine
export const WORKFLOW_ENGINE_TOKEN = Symbol('WORKFLOW_ENGINE_TOKEN');
export const BEHAVIOR_ENGINE_TOKEN = Symbol('BEHAVIOR_ENGINE_TOKEN');
export const WORKFLOW_SCHEMA_REPO_TOKEN = Symbol('WORKFLOW_SCHEMA_REPO_TOKEN');

// Session Layer
export const SESSION_REPO_TOKEN = Symbol('SESSION_REPO_TOKEN');
export const SESSION_MESSAGE_REPO_TOKEN = Symbol('SESSION_MESSAGE_REPO_TOKEN');
export const RUN_ENGINE_TOKEN = Symbol('RUN_ENGINE_TOKEN');
export const SESSION_RUN_COORDINATOR_TOKEN = Symbol('SESSION_RUN_COORDINATOR_TOKEN');
export const TASK_RUN_COORDINATOR_TOKEN = Symbol('TASK_RUN_COORDINATOR_TOKEN');
export const SESSION_SERVICE_TOKEN = Symbol('SESSION_SERVICE_TOKEN');

// Conversation System
export const CONVERSATION_WORKFLOW_REPO_TOKEN = Symbol('CONVERSATION_WORKFLOW_REPO_TOKEN');
export const ROUTING_POLICY_ENGINE_TOKEN = Symbol('ROUTING_POLICY_ENGINE_TOKEN');
export const CONVERSATION_WORKFLOW_SERVICE_TOKEN = Symbol('CONVERSATION_WORKFLOW_SERVICE_TOKEN');
export const TIMEOUT_ESCALATION_SERVICE_TOKEN = Symbol('TIMEOUT_ESCALATION_SERVICE_TOKEN');
export const CONVERSATION_CONTEXT_BUILDER_TOKEN = Symbol('CONVERSATION_CONTEXT_BUILDER_TOKEN');

// System
export const SYSTEM_CHECK_SERVICE_TOKEN = Symbol('SYSTEM_CHECK_SERVICE_TOKEN');
