// Infrastructure
export const CONFIG_TOKEN = Symbol('CONFIG_TOKEN');
export const LOGGER_TOKEN = Symbol('LOGGER_TOKEN');
export const SQLITE_CONNECTION_TOKEN = Symbol('SQLITE_CONNECTION_TOKEN');
export const EVENT_BUS_TOKEN = Symbol('EVENT_BUS_TOKEN');
export const EVENT_PUBLISHER_TOKEN = Symbol('EVENT_PUBLISHER_TOKEN');
export const OUTBOX_REPO_TOKEN = Symbol('OUTBOX_REPO_TOKEN');

// Organization Module
export const ORGANIZATION_REPO_TOKEN = Symbol('ORGANIZATION_REPO_TOKEN');
export const ROLE_REPO_TOKEN = Symbol('ROLE_REPO_TOKEN');
export const SKILL_REPO_TOKEN = Symbol('SKILL_REPO_TOKEN');

// Workflow Module
export const TASK_REPO_TOKEN = Symbol('TASK_REPO_TOKEN');
export const TASK_SERVICE_TOKEN = Symbol('TASK_SERVICE_TOKEN');
export const TASK_STATE_MACHINE_TOKEN = Symbol('TASK_STATE_MACHINE_TOKEN');
export const PROCESS_ENGINE_TOKEN = Symbol('PROCESS_ENGINE_TOKEN');
export const BEHAVIOR_ENGINE_TOKEN = Symbol('BEHAVIOR_ENGINE_TOKEN');
export const PROCESS_SCHEMA_REPO_TOKEN = Symbol('PROCESS_SCHEMA_REPO_TOKEN');
export const PROCESS_TEMPLATE_SERVICE_TOKEN = Symbol('PROCESS_TEMPLATE_SERVICE_TOKEN');

// Conversation Module
export const CONVERSATION_REPO_TOKEN = Symbol('CONVERSATION_REPO_TOKEN');
export const CONVERSATION_MESSAGE_REPO_TOKEN = Symbol('CONVERSATION_MESSAGE_REPO_TOKEN');
export const CONVERSATION_SERVICE_TOKEN = Symbol('CONVERSATION_SERVICE_TOKEN');
export const INQUIRY_ROUTER_TOKEN = Symbol('INQUIRY_ROUTER_TOKEN');
export const INQUIRY_ESCALATION_SERVICE_TOKEN = Symbol('INQUIRY_ESCALATION_SERVICE_TOKEN');
export const CONVERSATION_CONTEXT_BUILDER_TOKEN = Symbol('CONVERSATION_CONTEXT_BUILDER_TOKEN');

// Execution (Runtime)
export const RUN_ENGINE_TOKEN = Symbol('RUN_ENGINE_TOKEN');
export const EXECUTOR_TOKEN = Symbol('EXECUTOR_TOKEN');
export const WORKER_SERVICE_TOKEN = Symbol('WORKER_SERVICE_TOKEN');
export const RUN_REPO_TOKEN = Symbol('RUN_REPO_TOKEN');
export const COST_ENTRY_REPO_TOKEN = Symbol('COST_ENTRY_REPO_TOKEN');

// Prompt (Integration)
export const PROMPT_BUILDER_TOKEN = Symbol('PROMPT_BUILDER_TOKEN');
export const RUN_CONTEXT_TOKEN = Symbol('RUN_CONTEXT_TOKEN');

// MCP Bridge (Integration)
export const MCP_IPC_SERVER_TOKEN = Symbol('MCP_IPC_SERVER_TOKEN');
export const MCP_TOOL_REGISTRY_TOKEN = Symbol('MCP_TOOL_REGISTRY_TOKEN');

// Orchestrator & RunCoordinator
export const TASK_ORCHESTRATOR_TOKEN = Symbol('TASK_ORCHESTRATOR_TOKEN');
export const CONVERSATION_ORCHESTRATOR_TOKEN = Symbol('CONVERSATION_ORCHESTRATOR_TOKEN');
export const RUN_ORCHESTRATOR_TOKEN = Symbol('RUN_ORCHESTRATOR_TOKEN');
export const RUN_COORDINATOR_TOKEN = Symbol('RUN_COORDINATOR_TOKEN');
export const PENDING_WAKE_REPO_TOKEN = Symbol('PENDING_WAKE_REPO_TOKEN');

// Planning
export const PLANNING_SERVICE_TOKEN = Symbol('PLANNING_SERVICE_TOKEN');

// Notification
export const NOTIFICATION_SERVICE_TOKEN = Symbol('NOTIFICATION_SERVICE_TOKEN');
export const EVENT_BROADCASTER_TOKEN = Symbol('EVENT_BROADCASTER_TOKEN');

// System
export const SETTINGS_REPO_TOKEN = Symbol('SETTINGS_REPO_TOKEN');
export const SYSTEM_CHECK_SERVICE_TOKEN = Symbol('SYSTEM_CHECK_SERVICE_TOKEN');
